const TG_BLUE = "#2AABEE";
const TG_DARK_BLUE = "#1D8FCA";

export const Colors = {
  light: {
    primary: TG_BLUE,
    primaryDark: TG_DARK_BLUE,
    background: "#FFFFFF",
    secondaryBackground: "#F2F2F7",
    surface: "#FFFFFF",
    surfaceSecondary: "#F0F0F0",
    text: "#000000",
    textSecondary: "#8E8E93",
    textTertiary: "#C7C7CC",
    separator: "#E5E5EA",
    tint: TG_BLUE,
    tabIconDefault: "#8E8E93",
    tabIconSelected: TG_BLUE,
    messageBubbleSent: "#2AABEE",
    messageBubbleReceived: "#F0F0F0",
    messageSentText: "#FFFFFF",
    messageReceivedText: "#000000",
    inputBackground: "#F2F2F7",
    statusOnline: "#4CAF50",
    star: "#FFD700",
    premium: "#FFD700",
    error: "#FF3B30",
    success: "#34C759",
    warning: "#FF9500",
    overlay: "rgba(0,0,0,0.5)",
    headerBackground: "#FFFFFF",
    headerText: "#000000",
    link: TG_BLUE,
    badge: "#FF3B30",
    destructive: "#FF3B30",
    checkmark: TG_BLUE,
  },
  dark: {
    primary: TG_BLUE,
    primaryDark: TG_DARK_BLUE,
    background: "#1C1C1E",
    secondaryBackground: "#2C2C2E",
    surface: "#2C2C2E",
    surfaceSecondary: "#3A3A3C",
    text: "#FFFFFF",
    textSecondary: "#8E8E93",
    textTertiary: "#48484A",
    separator: "#38383A",
    tint: TG_BLUE,
    tabIconDefault: "#8E8E93",
    tabIconSelected: TG_BLUE,
    messageBubbleSent: "#2AABEE",
    messageBubbleReceived: "#2C2C2E",
    messageSentText: "#FFFFFF",
    messageReceivedText: "#FFFFFF",
    inputBackground: "#2C2C2E",
    statusOnline: "#4CAF50",
    star: "#FFD700",
    premium: "#FFD700",
    error: "#FF453A",
    success: "#30D158",
    warning: "#FF9F0A",
    overlay: "rgba(0,0,0,0.7)",
    headerBackground: "#1C1C1E",
    headerText: "#FFFFFF",
    link: TG_BLUE,
    badge: "#FF453A",
    destructive: "#FF453A",
    checkmark: TG_BLUE,
  },
};

export default Colors;
